name: sil_app_wrapper
description: Wrapper entry point the provides app wide dependencies
version: 0.0.1
author: dmwangi@savannahinformatics.com
homepage: https://gitlab.slade360emr.com/optimalhealth/sil_dart_utils
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  camera: ^0.8.0
  flutter:
    sdk: flutter
  local_auth: ^1.1.0
  sil_graphql_client:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_graphql_client.git
      ref: 0.0.5-nullsafety

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mockito: ^5.0.1
  test:
  test_api: ">=0.2.19"

flutter:
