name: app_wrapper
description: A wrapper that is responsible for initializing various services and utilities needed to run apps safely.
version: 0.1.35
homepage: https://github.com/savannahghi/app_wrapper
repository: https://github.com/savannahghi/app_wrapper
issue_tracker: https://github.com/savannahghi/app_wrapper/issues
documentation: https://github.com/savannahghi/app_wrapper/blob/main/doc/readme.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  camera: ^0.8.1+4
  flutter:
    sdk: flutter
  flutter_graphql_client: ^0.1.24
  local_auth: ^1.1.6

dev_dependencies:
  build_runner: ^2.0.4
  camera_platform_interface: ^2.0.1
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.10
  test:
  test_api: ">=0.2.19"

flutter:
