name: app_wrapper
description: Wrapper entry point the provides app wide dependencies
version: 0.1.1
homepage: https://github.com/savannahghi/app_wrapper
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  camera: ^0.8.1+2
  flutter:
    sdk: flutter
  local_auth: ^1.1.6
  sil_graphql_client:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_graphql_client.git
      ref: 0.1.01

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.10
  test:
  test_api: ">=0.2.19"

flutter:
